name: 'SWM GitHub Actions Basic'

on:
  push:
    branches:
    - main
    tags:
    - 'v*'
  pull_request:
    branches:
    - main

jobs:
  first-job:
    name: 'First Job'

    runs-on: 'ubuntu-latest'

    steps:
    - name: 'Say Hello World 1'
      shell: pwsh
      run: |
        echo "hello world from first job"

  second-job:
    name: 'Second Job'
    needs: first-job

    runs-on: 'ubuntu-latest'

    steps:
    - name: 'Say Hello World 2'
      shell: pwsh
      run: |
        echo "hello world from second job"

  third-job:
    name: 'Third Job'
    needs: second-job

    runs-on: 'ubuntu-latest'

    steps:
    - name: 'Say Hello World 3'
      shell: pwsh
      run: |
        echo "hello world from third job"
